project_id = "yrxdnghjboolchwsfrqk"

[auth]
enabled = true
# ถ้า dev ใช้ Vite port 8080 ให้ตั้งเป็น 8080
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "https://dda03c62-e512-49be-aa0e-9bfaf060e4a1.lovableproject.com/**",
  "https://id-preview--dda03c62-e512-49be-aa0e-9bfaf060e4a1.lovable.app/**",
  "https://preview--wander-voice.lovable.app/**",
  "https://wander-voice.lovable.app/**"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.rate_limit]
inactivity_timeout = "0s"

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

